### ISSUE TITLE
Add Mime-Type on response

### ISSUE THREAD

**Issue by xkill** [jazzband/django-ical#33]
Hi,

I miss the mime-type on the response header to allow desktop and mobile apps to use the calendar feed on the calendar application.

Header:
```
application/hbs-vcs, text/calendar, text/x-vcalendar
```

**Comment by aleksihakli** [comment]
Good catch!

**Comment by aleksihakli** [comment]
Released in 1.7.0.

**Comment by aleksihakli** [comment]
@xkill this unfortunately needs to be rolled back since the Content-Type header can not contain multiple values per specification. The correct behaviour would be for the client to define an accepted content type with the Accept header and then the server to set the proper Content-Type per that header in response if it can reply with the proper type.
