### ISSUE TITLE
Add VALARM option

### ISSUE THREAD

**Issue by podplatnikm** [jazzband/django-ical#46]
Hello all!

For my project, I need to specify alarms/notifications for an .ical file I'm building. But there are no hooks or method I can return the Alarm object like I can return Items/Events. Am I missing something, how can I get around this. Are you planning to add a VALARM option in the future?

Best regards

**Comment by aleksihakli** [comment]
Hi @podplatnikm :) If you need the valarm option, I'd see it best to open a PR for the repo since you already know the requirements, and the code could benefit other users as well. Would you be interested in that? 

As far as I've understood this is the element you are referring to?

- https://en.wikipedia.org/wiki/ICalendar#Events_(VEVENT)
- https://www.kanzaki.com/docs/ical/valarm.html

**Comment by malteger** [comment]
I am also interested in this and will have a look and then submit a pull request

**Comment by aleksihakli** [comment]
Documentation now has documentation on alarms:

https://django-ical.readthedocs.io/en/latest/usage.html#alarms

Feature will be available on version 1.8.0+ on PyPI soon.
